[package]
name = "tron_vanity_balance_mixed"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
secp256k1 = { version = "0.26", features = ["rand"] }
sha3 = "0.10"
bs58 = "0.4"
rayon = "1.7"
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.42", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ocl = "0.19.7"
indicatif = "0.17"
